# Generated by Django 2.2.15 on 2020-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_url',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='URL'),
        ),
    ]
