# Generated by Django 2.2.15 on 2020-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpage_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='meetup_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Meetup image url'),
        ),
    ]
