# Generated by Django 2.2.6 on 2019-11-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191111_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción'),
        ),
    ]
