# Generated by Django 2.2.6 on 2019-12-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_generalpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpage',
            name='date',
        ),
    ]
